// this file will be used to define the action types

//Home Page Action Types
export const SET_MATERIAL_LIST = 'SET_MATERIAL_LIST'
export const SET_SELECTED_MATERIAL_ID = 'SET_SELECTED_MATERIAL_ID'

//Order Page Action Types
export const FETCH_ORDER_LIST = 'FETCH_ORDER_LIST'
export const ADD_TIMELINE_DATA_BY_INDEX = 'ADD_TIMELINE_DATA_BY_INDEX'
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'
export const FETCH_STEP_INFO = 'FETCH_STEP_INFO'
export const TOGGLE_DESIGN_SELECTION = 'TOGGLE_DESIGN_SELECTION'
export const SELECT_ALL_DESIGN = 'SELECT_ALL_DESIGN'
export const CLEAR_DESIGN_SELECTION = 'CLEAR_DESIGN_SELECTION'
export const FETCH_ORDER_INFO_LIST = 'FETCH_ORDER_INFO_LIST'
export const FETCH_TIMELINE_LIST = 'FETCH_TIMELINE_LIST'
export const CLEAR_TIMELINE_DATA = 'CLEAR_TIMELINE_DATA'
export const GENERATE_TIMELINE_PARAMS = 'GENERATE_TIMELINE_PARAMS'

// Moodboard Action Types
export const SET_MOODBOARD_LIST = 'SET_MOODBOARD_LIST'
export const SET_MOODBOARD_BY_ID = 'SET_MOODBOARD_BY_ID'
export const UPDATE_SELECTED_MOODBOARD_STATE = 'UPDATE_SELECTED_MOODBOARD_STATE'
export const SET_COLOR_CODES = 'SET_COLOR_CODES'
export const SET_MOODBOARD_FABRICS = 'SET_MOODBOARD_FABRICS'
export const SET_FAVOURITE_MOODBOARD = 'SET_FAVOURITE_MOODBOARD'
export const UNSET_FAVOURITE_MOODBOARD = 'UNSET_FAVOURITE_MOODBOARD'
