// this file will be used to define the action types

//Home Page Action Types
export const SET_MATERIAL_LIST = 'SET_MATERIAL_LIST'
export const SET_SELECTED_MATERIAL_ID = 'SET_SELECTED_MATERIAL_ID'

// Moodboard Action Types
export const SET_MOODBOARD_LIST = 'SET_MOODBOARD_LIST'
export const SET_MOODBOARD_BY_ID = 'SET_MOODBOARD_BY_ID'
export const UPDATE_SELECTED_MOODBOARD_STATE = 'UPDATE_SELECTED_MOODBOARD_STATE'
export const SET_COLOR_CODES = 'SET_COLOR_CODES'
export const SET_MOODBOARD_FABRICS = 'SET_MOODBOARD_FABRICS'
export const SET_FAVOURITE_MOODBOARD = 'SET_FAVOURITE_MOODBOARD'
export const UNSET_FAVOURITE_MOODBOARD = 'UNSET_FAVOURITE_MOODBOARD'
