export const FETCH_POM_AND_SIZE_REQUEST = "FETCH_POM_AND_SIZE_REQUEST";
export const FETCH_POM_AND_SIZE_SUCCESS = "FETCH_POM_AND_SIZE_SUCCESS";
export const FETCH_POM_AND_SIZE_FAILURE = "FETCH_POM_AND_SIZE_FAILURE";

export const FETCH_PRODUCT_MEASUREMENT_REQUEST = "FETCH_PRODUCT_MEASUREMENT_REQUEST";
export const FETCH_PRODUCT_MEASUREMENT_SUCCESS = "FETCH_PRODUCT_MEASUREMENT_SUCCESS";
export const FETCH_PRODUCT_MEASUREMENT_FAILURE = "FETCH_PRODUCT_MEASUREMENT_FAILURE";

export const FETCH_ALL_TEMPLATE_REQUEST = "FETCH_ALL_TEMPLATE_REQUEST";
export const FETCH_ALL_TEMPLATE_SUCCESS = "FETCH_ALL_TEMPLATE_SUCCESS";
export const FETCH_ALL_TEMPLATE_FAILURE = "FETCH_ALL_TEMPLATE_FAILURE";
