export const FETCH_DASHBOARD_QUOTES_SUCCESS = "FETCH_DASHBOARD_QUOTES_SUCCESS";
export const FETCH_MORE_DASHBOARD_QUOTES_SUCCESS = "FETCH_MORE_DASHBOARD_QUOTES_SUCCESS";
export const FETCH_DASHBOARD_QUOTES_FAILURE = "FETCH_DASHBOARD_QUOTES_FAILURE";

export const FETCH_DASHBOARD_ALL_TASKS_SUCCESS = "FETCH_DASHBOARD_ALL_TASKS_SUCCESS";
export const FETCH_MORE_DASHBOARD_ALL_TASKS_SUCCESS = "FETCH_MORE_DASHBOARD_ALL_TASKS_SUCCESS";
export const FETCH_DASHBOARD_ALL_TASKS_FAILURE = "FETCH_DASHBOARD_ALL_TASKS_FAILURE";
