export const ActionTypes = {
    FETCH_ORDER_LIST: "FETCH_ORDER_LIST",
    FETCH_TIMELINE_LIST: "FETCH_TIMELINE_LIST",
    FETCH_ORDER_INFO_LIST: "FETCH_ORDER_INFO_LIST",
    CLEAR_DESIGN_SELECTION: "CLEAR_DESIGN_SELECTION",
    SELECT_ALL_DESIGN: "SELECT_ALL_DESIGN",
    TOGGLE_DESIGN_SELECTION: "TOGGLE_DESIGN_SELECTION",
    FETCH_STEP_INFO: "FETCH_STEP_INFO",
}