// Here we will hold all the types of thunks
// Thunks are for me async tasks that need network transaction

//Home Page Thunks
export const GET_MATERIAL_LIST_BY_FABRIC_TYPE =
    'GET_MATERIAL_LIST_BY_FABRIC_TYPE'
export const GET_PRODUCT_BY_MATERIAL_ID = 'GET_PRODUCT_BY_MATERIAL_ID'

// Moodboard Thunks
export const GET_MOODBOARD_LIST = 'GET_MOODBOARD_LIST'
export const GET_MOODBOARD_BY_ID = 'GET_MOODBOARD_BY_ID'
export const UPLOAD_MOODBOARDS = 'UPLOAD_MOODBOARDS'
export const UPDATE_MOODBOARD = 'UPDATE_MOODBOARD'
export const UPLOAD_MOODBOARD_IMAGES = 'UPLOAD_MOODBOARD_IMAGES'
export const GET_COLOR_CODES = 'GET_COLOR_CODES'
export const DELETE_PRODUCT_IMAGE = 'DELETE_PRODUCT_IMAGE'
export const ADD_COLOR_CODE = 'ADD_COLOR_CODE'
export const DELETE_COLOR_FROM_MOODBOARD = 'DELETE_COLOR_FROM_MOODBOARD'
export const GET_MOODBOARD_FABRICS = 'GET_MOODBOARD_FABRICS'
